// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-Co4qwtDp4dQ4Z3ljnwH3WFmoN-E7vCY',
    appId: '1:92411189282:web:a5e955ebc3a7f99c86527b',
    messagingSenderId: '92411189282',
    projectId: 'food-algorithm-recommend',
    authDomain: 'food-algorithm-recommend.firebaseapp.com',
    storageBucket: 'food-algorithm-recommend.appspot.com',
    measurementId: 'G-ENV4X5EX4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_guvYdCS3WXfONIx8yq7ZNhlcLOy9Mio',
    appId: '1:92411189282:android:5a1b714a61c379d586527b',
    messagingSenderId: '92411189282',
    projectId: 'food-algorithm-recommend',
    storageBucket: 'food-algorithm-recommend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKdsg6zb9xtDtv6kxQdrcHCJR1IaC2_lk',
    appId: '1:92411189282:ios:98893cb4c9fa793d86527b',
    messagingSenderId: '92411189282',
    projectId: 'food-algorithm-recommend',
    storageBucket: 'food-algorithm-recommend.appspot.com',
    iosClientId:
        '92411189282-kmun7rd7hu1hpvlvb0kddud8vmr0l416.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodAlgorithmRecommend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKdsg6zb9xtDtv6kxQdrcHCJR1IaC2_lk',
    appId: '1:92411189282:ios:98893cb4c9fa793d86527b',
    messagingSenderId: '92411189282',
    projectId: 'food-algorithm-recommend',
    storageBucket: 'food-algorithm-recommend.appspot.com',
    iosClientId:
        '92411189282-kmun7rd7hu1hpvlvb0kddud8vmr0l416.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodAlgorithmRecommend',
  );
}
